[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
testpaths = apps
addopts = -q --cov --cov-report=term-missing:skip-covered --cov-fail-under=85
filterwarnings =
    ignore::DeprecationWarning
