# Generated by Django 5.2.15 on 2026-07-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('entity_type', models.CharField(max_length=64, verbose_name='Тип объекта')),
                ('entity_id', models.CharField(max_length=64, verbose_name='ID объекта')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='До')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='После')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
