# Generated by Django 5.2.15 on 2026-07-03 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('salary_type', models.CharField(choices=[('objective', 'Объектный'), ('administrative', 'Административный')], max_length=20, verbose_name='Тип оплаты')),
                ('is_salesperson', models.BooleanField(default=False, verbose_name='Продажник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('business', models.ForeignKey(blank=True, help_text='Пусто для административного персонала головного офиса', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Утверждён')], default='draft', max_length=12, verbose_name='Статус')),
                ('paid_from_hq', models.BooleanField(default=True, verbose_name='Выплата из головного офиса')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Утверждён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Расчёт зарплаты',
                'verbose_name_plural': 'Расчёты зарплаты',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Оклад')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Бонус')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итого')),
                ('breakdown', models.JSONField(default=dict, verbose_name='Разбивка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='payroll.employee', verbose_name='Сотрудник')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payroll.payrollrun', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Строка расчёта',
                'verbose_name_plural': 'Строки расчёта',
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('scheme_type', models.CharField(choices=[('fixed', 'Оклад'), ('percent_of_sales', 'Процент от продаж'), ('per_unit_tiered', 'За единицу со ступенями')], max_length=32, verbose_name='Тип схемы')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='payroll.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Схема зарплаты',
                'verbose_name_plural': 'Схемы зарплаты',
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='payroll_run_period_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='payroll_item_unique_per_run'),
        ),
    ]
