# Generated by Django 5.2.15 on 2026-07-03 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('kind', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=10, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('void', 'Аннулировано')], default='pending', max_length=10, verbose_name='Статус')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.business', verbose_name='Бизнес')),
                ('category', models.ForeignKey(blank=True, help_text='Обязательна для расхода, пуста для прихода', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.expensecategory', verbose_name='Категория')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['business', 'kind', 'status'], name='finance_tra_busines_65d265_idx'), models.Index(fields=['occurred_at'], name='finance_tra_occurre_a7816a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_tx_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'expense'), _negated=True), ('category__isnull', False), _connector='OR'), name='finance_expense_requires_category')],
            },
        ),
    ]
