# Generated by Django 5.2.15 on 2026-07-03 10:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('description', models.TextField(verbose_name='Описание')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Оценка')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=10, verbose_name='Статус')),
                ('business_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barters_a', to='core.business', verbose_name='Сторона А')),
                ('business_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barters_b', to='core.business', verbose_name='Сторона Б')),
                ('controlled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_barters', to=settings.AUTH_USER_MODEL, verbose_name='Контролирует (бухгалтер)')),
            ],
            options={
                'verbose_name': 'Бартер',
                'verbose_name_plural': 'Бартеры',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts_receivable', to='core.business', verbose_name='Кредитор')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts_owed', to='core.business', verbose_name='Должник')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DebtSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('offset', 'Взаимозачёт'), ('return', 'Возврат')], max_length=10, verbose_name='Способ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('barter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_settlements', to='settlements.barter', verbose_name='Бартер')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_settlements', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='settlements.debt', verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Погашение долга',
                'verbose_name_plural': 'Погашения долгов',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус')),
                ('requires_owner_approval', models.BooleanField(default=False, verbose_name='Требует одобрения владельцем')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.business', verbose_name='Откуда')),
                ('to_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.business', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Передача',
                'verbose_name_plural': 'Передачи',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='source_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='settlements.transfer', verbose_name='Из передачи'),
        ),
        migrations.AddConstraint(
            model_name='barter',
            constraint=models.CheckConstraint(condition=models.Q(('business_a', models.F('business_b')), _negated=True), name='settlements_barter_not_self'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_business', models.F('to_business')), _negated=True), name='settlements_transfer_not_self'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlements_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('debtor', models.F('creditor')), _negated=True), name='settlements_debt_not_self'),
        ),
    ]
