# Generated by Django 5.2.15 on 2026-07-03 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoperation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_operations', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='core.business', verbose_name='Бизнес'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные'),
        ),
        migrations.AddField(
            model_name='cashoperation',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='cash.cashregister', verbose_name='Касса'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='cash_register_name_unique_per_business'),
        ),
        migrations.AddIndex(
            model_name='cashoperation',
            index=models.Index(fields=['register', 'occurred_at'], name='cash_cashop_registe_500cf5_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashoperation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_op_amount_positive'),
        ),
    ]
